using System.Collections.Generic;

namespace FrontEnd
{
    public class Config
    {
        public static Dictionary<string, string> itemNameToIdDictionary = new()
        {
            { "2592", "potionofdefense" },
            { "2591", "potionofattack" },
            { "2593", "potionofspeed" },
            { "2636", "potionofdexterity" },
            { "2613", "potionofwisdom" },
            { "2612", "potionofvitality" },
            { "2794", "potionofmana" },
            { "2793", "potionoflife" },
            { "116", "anystatpot" },
            { "9065", "greaterpotionofdefense" },
            { "9064", "greaterpotionofattack" },
            { "9066", "greaterpotionofspeed" },
            { "9069", "greaterpotionofdexterity" },
            { "9068", "greaterpotionofwisdom" },
            { "9067", "greaterpotionofvitality" },
            { "9071", "greaterpotionofmana" },
            { "9070", "greaterpotionoflife" },
            { "1826", "winecellarincantation" },
            { "10024", "helmetrune" },
            { "10023", "shieldrune" },
            { "10022", "swordrune" },
            { "1808", "tomboftheancientskey" },
            { "3089", "oceantrenchkey" },
            { "1802", "abyssofdemonskey" },
            { "3107", "manorkey" },
            { "3133", "beachzonekey" },
            { "3170", "candykey" },
            { "3278", "deadwaterdockskey" },
            { "3311", "battlenexuskey" },
            { "3293", "shatterskey" },
            { "8852", "shaitan'skey" },
            { "29804", "puppetmaster'sencorekey" },
            { "303", "mountaintemplekey" },
            { "4252", "thenestkey" },
            { "2991", "losthallskey" },
            { "2555", "reefkey" },
            { "3872", "madgodmayhemkey" },
            { "13984", "secludedthicketkey" },
            { "1404", "cursedlibrarykey" },
            { "9326", "heroicundeadlairkey" },
            { "9325", "heroicabyssofdemonskey" },
            { "1413", "malogiakey" },
            { "1415", "foraxkey" },
            { "1412", "fungalcavernkey" },
            { "19301", "thethirddimensionkey" },
            { "1799", "healingichor" },
            { "3105", "holywater" },
            { "2868", "firewater" },
            { "2875", "muscat" },
            { "2871", "melonliqueur" },
            { "3090", "coraljuice" },
            { "2736", "minorhealthpotion" },
            { "2781", "minormagicpotion" },
            { "3109", "ghostpiraterum" },
            { "3137", "transformationpotion" },
            { "3267", "saintpaddy'sbrew" },
            { "3129", "bahamasunrise" },
            { "3130", "blueparadise" },
            { "3131", "pinkpassionbreeze" },
            { "3132", "limejunglebay" },
            { "1409", "serverheart" },
            { "2835", "effusionofdefense" },
            { "3436", "effusionofattack" },
            { "3437", "effusionofspeed" },
            { "2832", "effusionofdexterity" },
            { "3439", "effusionofwisdom" },
            { "3438", "effusionofvitality" },
            { "2833", "effusionoflife" },
            { "3432", "tinctureofattack" },
            { "3433", "tinctureofspeed" },
            { "2828", "tinctureofdexterity" },
            { "19080", "amaranthnildrop" },
            { "19083", "scarletnildrop" },
            { "19085", "azurenildrop" },
            { "19084", "crimsonnildrop" },
            { "19086", "hazelnildrop" },
            { "19087", "tealnildrop" },
            { "19079", "forcenildrop" },
            { "19078", "cindernildrop" },
            { "9077", "bloodnildrop" },
            { "2799", "whitedrakeegg" },
            { "2800", "bluedrakeegg" },
            { "2801", "orangedrakeegg" },
            { "2802", "greendrakeegg" },
            { "2641", "magicmushroom" },
            { "5407", "valentine" },
            { "14271", "forgottenlogii" },
            { "8779", "potionofhealth1" },
            { "8798", "potionofhealth2" },
            { "8814", "slimearcherskin" },
            { "8815", "brigandskin" },
            { "8827", "agentskin" },
            { "8828", "slimeknightskin" },
            { "8829", "slimepriestskin" },
            { "8830", "bashingbrideskin" },
            { "8831", "eligiblebachelorskin" },
            { "8858", "nunskin" },
            { "8859", "witchdoctorskin" },
            { "8860", "sorceressskin" },
            { "8861", "artemisskin" },
            { "8781", "shoveguyskin" },
            { "8812", "scarlettskin" },
            { "9615", "slimeninjaskin" },
            { "8850", "slimewizardskin" },
            { "8851", "deadlyvixenskin" },
            { "8856", "stanleythespringbunnyskin" },
            { "8993", "nexusnomikoskin" },
            { "8995", "drowtricksterskin" },
            { "8983", "b.b.wolfskin" },
            { "8984", "lilredskin" },
            { "8783", "holyavengerskin" },
            { "8796", "rangerskin" },
            { "8985", "kingknifeulaskin" },
            { "9011", "witchskin" },
            { "8980", "platinumknightskin" },
            { "8981", "platinumwarriorskin" },
            { "8982", "platinumrogueskin" },
            { "9033", "slimesorcererskin" },
            { "9034", "slimetricksterskin" },
            { "9035", "slimemysticskin" },
            { "9036", "slimehuntressskin" },
            { "9037", "slimenecromancerskin" },
            { "9038", "slimeassassinskin" },
            { "9039", "slimepaladinskin" },
            { "9040", "slimerogueskin" },
            { "9041", "slimewarriorskin" },
            { "29769", "puppetmasterskin" },
            { "9074", "ghosthuntressskin" },
            { "9075", "skeletonwarriorskin" },
            { "29819", "huntsmanskin" },
            { "29820", "demonspawnskin" },
            { "29821", "hunchbackskin" },
            { "29822", "vampiressskin" },
            { "29823", "frankensteinsmonsterskin" },
            { "29824", "jacktheripperskin" },
            { "29825", "deathskin" },
            { "29826", "tinyavatarskin" },
            { "20827", "zombienurseskin" },
            { "29828", "ascendedsorcererskin" },
            { "29829", "mischievousimpskin" },
            { "29830", "vampirehunterskin" },
            { "29831", "poltergeistskin" },
            { "29832", "darkelfhuntressskin" },
            { "9076", "infectedskin" },
            { "3312", "santaskin" },
            { "3313", "littlehelperskin" },
            { "3320", "icemanskin" },
            { "6874", "santatricksterskin" },
            { "8319", "oryxmasrogueskin" },
            { "8320", "oryxmasarcherskin" },
            { "8321", "oryxmaswizardskin" },
            { "8322", "oryxmaspriestskin" },
            { "8323", "oryxmaswarriorskin" },
            { "8324 ", "oryxmasknightskin" },
            { "8325", "oryxmaspaladinskin" },
            { "8326", "oryxmasassassinskin" },
            { "8327", "oryxmasnecromancerskin" },
            { "8328", "oryxmashuntressskin" },
            { "8329", "oryxmasmysticskin" },
            { "8330", "oryxmastricksterskin" },
            { "8331", "oryxmassorcererskin" },
            { "8332", "oryxmasninjaskin" },
            { "19660", "oryxmassamuraiskin" },
            { "9382", "slimebardskin" },
            { "9390", "oryxmasbardskin" },
            { "30720", "slimesummonerskin" },
            { "30804", "oryxmassummonerskin" },
            { "31233", "oryxmaskenseiskin" },
            { "2721", "staffofdiabolicsecretst10" },
            { "2722", "staffofastralknowledget11" },
            { "2824", "staffofthecosmicwholet12" },
            { "2513", "staffofthevitalunityt13" },
            { "3075", "staffofextremeprejudiceut" },
            { "5847 ", "staffoficeblastut" },
            { "3108", "anatisstaffut" },
            { "3306", "koalapowut" },
            { "8843", "staffofadorationut" },
            { "8857", "staffoftherisingsunut" },
            { "8998", "barelyattunedmagicthingyut" },
            { "3859", "staffofhorrificknowledgeut" },
            { "9059", "thephylacteryut" },
            { "9086", "staffofyuletidecarolsut" },
            { "8615", "legacysentientstaffut" },
            { "14493", "staffofsilverwingsut" },
            { "2112", "spiritstaffut" },
            { "25688", "foramitestaffut" },
            { "6860", "frosty'swalkingstickut" },
            { "1894", "staffofesbenut" },
            { "12069", "screwdriverstaffut" },
            { "20977", "staffofthesaintut" },
            { "1394", "k.i.d.d.forceut" },
            { "2694", "wandofshadowt10" },
            { "2695", "wandofancientwarningt11" },
            { "2806", "wandofrecompenset12" },
            { "2506", "wandofevocationt13" },
            { "3076", "wandofthebulwarkut" },
            { "5848", "eternalsnowflakewandut" },
            { "3101", "st.abraham'swandut" },
            { "3123", "conductingwandut" },
            { "3307", "spicywandofspiceut" },
            { "8999", "lethargicsentienceut" },
            { "8854", "wandofegg" },
            { "3856", "wandofancientterrorut" },
            { "9055", "wandofgebut" },
            { "9084", "presentdispensingwandut" },
            { "14494", "wandofthesummonedoneut" },
            { "6861", "winter'sbreathwandut" },
            { "24834", "soul'sguidanceut" },
            { "1398", "caduceusofcurrentcrazinessut" },
            { "2635", "spritewandut" },
            { "2700", "bowoffeymagict10" },
            { "2701", "bowofinnocentbloodt11" },
            { "2818", "bowofcoverthavenst12" },
            { "2508", "bowofmysticalenergyt13" },
            { "6858", "iciclelauncherut" },
            { "3074", "doombowut" },
            { "8961", "bowofthemorningstarut" },
            { "25696", "sun'sjudgementut" },
            { "3088", "coralbowut" },
            { "5849", "arcticbowut" },
            { "3308", "robobowut" },
            { "8997", "preciselycalibratedstringstickut" },
            { "9610", "bowofeternalfrostut" },
            { "14492", "bowofthesky'sgloryut" },
            { "12067", "nailgunbowut" },
            { "5706", "cloverbowut" },
            { "1397", "butterbowut" },
            { "2697", "emeraldsharddaggert10" },
            { "2698", "agateclawdaggert11" },
            { "2815", "daggeroffoulmalevolencet12" },
            { "2502", "daggerofsinisterdeedst13" },
            { "2849", "chickenlegofdoomut" },
            { "3106", "bonedaggerut" },
            { "3113", "spiritdaggerut" },
            { "1801", "poisonfangdaggerut" },
            { "3309", "sunshineshivut" },
            { "8845", "heartfinddaggerut" },
            { "9002", "daggeroftheamethystprismut" },
            { "9000", "toyknifeut" },
            { "3857", "daggeroftheterribletalonut" },
            { "8608", "legacyetheritedaggerut" },
            { "9085", "anicicleut" },
            { "14491", "daggerofeternalchaosut" },
            { "12068", "spatuladaggerut" },
            { "2201", "daggerofthehastefulrabbitut" },
            { "20983", "prismaticslasherut" },
            { "1408", "corruptioncutterut" },
            { "25698", "duelingdaggersut" },
            { "6859", "frostlich'sfingerut" },
            { "1396", "mistermangout" },
            { "2692", "archonswordt10" },
            { "2631", "skysplitterswordt11" },
            { "2827", "swordofacclaimt12" },
            { "2504", "swordofsplendort13" },
            { "3073", "demonbladeut" },
            { "8963", "swordofilluminationut" },
            { "3291", "pirateking'scutlassut" },
            { "3295", "doctorswordsworthut" },
            { "8732", "skull" },
            { "8846", "vineswordut" },
            { "9659", "arcanerapierut" },
            { "8962", "swordofthemadgodut" },
            { "8996", "unstableanomalyut" },
            { "9063", "legacypixie" },
            { "9612", "frostbiteut" },
            { "19212", "keychaincutlassut" },
            { "14495", "swordoftheunendingchaosut" },
            { "25691", "gaseousglaiveut" },
            { "5846", "enchantedicebladeut" },
            { "6862", "saintnicolas'bladeut" },
            { "12071", "hammerswordut" },
            { "1705", "apocalypsefeatherut" },
            { "5707", "swordoftherainbow'sendut" },
            { "23334", "silex'shammerut" },
            { "1395", "mmacemmurdererut" },
            { "3150", "ichimonjit10" },
            { "3151", "muramasat11" },
            { "3152", "masamunet12" },
            { "586", "sadamunet13" },
            { "3292", "dokunokenut" },
            { "3310", "arbiter'swrathut" },
            { "8842", "diamond" },
            { "3860", "corruptedcleaverut" },
            { "9087", "saljuut" },
            { "14497", "skyboundbladeut" },
            { "25693", "firebladeut" },
            { "12072", "sawbladekatanaut" },
            { "1399", "bladeofagesut" },
            { "29037", "voidbladeut" },
            { "6863", "yukiut" },
            { "23332", "krathanaut" },
            { "2709", "robeofthemoonwizardt11" },
            { "2710", "robeoftheelderwarlockt12" },
            { "2821", "robeofthegrandsorcerert13" },
            { "2511", "robeofthestarmothert14" },
            { "8863", "robeofthesummersolsticeut" },
            { "3103", "chasubleofholylightut" },
            { "3122", "robeofthemadscientistut" },
            { "3203", "cheaterrobeut" },
            { "3092", "robeofthetlatoaniut" },
            { "9052", "shendytofgebut" },
            { "9056", "soullessrobeut" },
            { "8616", "legacyrobeoftwilightut" },
            { "14499", "robeofdarksummoningut" },
            { "-19465", "esben'sshamanattireut" },
            { "5851", "frostelementalistrobeut" },
            { "12073", "magicconstructionvestut" },
            { "14074", "tlatoani'sshroudut" },
            { "2706", "vengeancearmort11" },
            { "2707", "abyssalarmort12" },
            { "2812", "acropolisarmort13" },
            { "2500", "dominionarmort14" },
            { "9015", "almandinearmorofangerut" },
            { "3169", "candy" },
            { "3182", "resurrectedwarrior'sarmorut" },
            { "3204", "cheaterheavyarmorut" },
            { "9060", "legacyfairyplateut" },
            { "14500", "armorofheavenlylightut" },
            { "5853", "frostcitadelarmorut" },
            { "12075", "heavyconstructionvestut" },
            { "2703", "hippogriffhidearmort11" },
            { "2704", "griffonhidearmort12" },
            { "2809", "hydraskinarmort13" },
            { "2497", "wyrmhidearmort14" },
            { "3096", "coralsilkarmorut" },
            { "3112", "spectralclotharmorut" },
            { "3202", "cheaterlightarmorut" },
            { "8609", "legacymantleofskuldut" },
            { "14498", "shadowbeasthideut" },
            { "4308", "beehemotharmorut" },
            { "12074", "fittedconstructionvestut" },
            { "5850", "frostdrakehidearmorut" },
            { "15717", "greaterhosenut" },
            { "29768", "harlequinarmorut" },
            { "2785", "cloakofendlesstwilightt5" },
            { "2855", "cloakofghostlyconcealmentt6" },
            { "2650", "cloakoftheplanewalkerut" },
            { "8610", "legacyghastlydrapeut" },
            { "8333", "cloakofwinterut" },
            { "2661", "goldenquivert5" },
            { "2856", "quiverofelvishmasteryt6" },
            { "8336", "coalbearingquiverut" },
            { "23337", "archerangut" },
            { "2608", "magicnovaspellt5" },
            { "2852", "elementaldetonationspellt6" },
            { "8862", "thousandsunsspellut" },
            { "8617", "legacyancientspell" },
            { "8338", "vigilspellut" },
            { "23330", "randomspellextractiondeviceut" },
            { "23339", "spellingspellut" },
            { "2651", "tomeofdivinefavort5" },
            { "2853", "tomeofholyguidancet6" },
            { "3081", "tomeofpurificationut" },
            { "9054", "bookofgebut" },
            { "8342", "nativitytomeut" },
            { "23341", "tomeofmoralsupportut" },
            { "1405", "necronomiconut" },
            { "2667", "goldenhelmt5" },
            { "2857", "helmofthegreatgeneralt6" },
            { "8335", "pathfinder'shelmut" },
            { "9661", "amberencrustedhelmetut" },
            { "2572", "mithrilshieldt5" },
            { "2850", "colossusshieldt6" },
            { "9017", "onyxshieldofthemadgodut" },
            { "2624", "snakeskinshieldut" },
            { "8340", "resoundingshieldut" },
            { "23344", "shieldofpogmurut" },
            { "2645", "sealoftheholywarriort5" },
            { "2854", "sealoftheblessedchampiont6" },
            { "9062", "legacysealoftheenchantedforestut" },
            { "8344", "adventsealut" },
            { "1406", "scholar'ssealut" },
            { "9660", "sandstonesealut" },
            { "2728", "nightwingvenomt5" },
            { "2858", "baneserpentpoisont6" },
            { "3181", "plaguepoisonut" },
            { "8343", "hollypoisonut" },
            { "15718", "mightysteinut" },
            { "23347", "lightninginabottleut" },
            { "29040", "murkytoxinut" },
            { "2735", "lifedrinkerskullt5" },
            { "2859", "bloodsuckerskullt6" },
            { "3094", "crackedcrystalskullut" },
            { "8337", "skullofkrampusut" },
            { "23349", "epiphanyskullut" },
            { "1895", "skullishremainsofesbenut" },
            { "13987", "sealedcrystalskullut" },
            { "2742", "dragonstalkertrapt5" },
            { "2860", "giantcatchertrapt6" },
            { "8339", "greedsnatchertraput" },
            { "25109", "painbowut" },
            { "19252", "mimicrytraput" },
            { "23351", "heliumtraput" },
            { "2630", "banishmentorbt5" },
            { "2861", "planefetterorbt6" },
            { "9058", "soulofthebearerut" },
            { "8334", "snowboundorbut" },
            { "2848", "prismofphantomst5" },
            { "2851", "prismofapparitionst6" },
            { "3114", "ghostlyprismut" },
            { "8341", "ornamentalprismut" },
            { "1904", "heartofgoldprismut" },
            { "2322", "prismofdancingswordsut" },
            { "23353", "fool'sprismut" },
            { "19254", "prismimicut" },
            { "2866", "scepterofskyboltst5" },
            { "2867", "scepterofstormst6" },
            { "3120", "scepteroffulminationut" },
            { "8346", "scepterofsainthoodut" },
            { "23354", "honeysceptersupremeut" },
            { "310", "honeyscepterut" },
            { "3160", "icestart5" },
            { "3161", "doomcirclet6" },
            { "8345", "ilexstarut" },
            { "23355", "unshurikenut" },
            { "29718", "cloverstarut" },
            { "6831", "jade" },
            { "6832", "royalwakizashit6" },
            { "613", "peppermintwakizashiut" },
            { "23357", "nsfwakizashiut" },
            { "1407", "ronin'swakizashiut" },
            { "-12298", "regallutet5" },
            { "-12297", "skywardlutet6" },
            { "12167", "oryxmascarolut" },
            { "19950", "snakecharmerpungiut" },
            { "14408", "monarchmacet5" },
            { "14409", "sovereignmacet6" },
            { "14341", "maceofthenorthpoleut" },
            { "14613", "serpentinesheatht5" },
            { "14614", "greatshinobisheatht6" },
            { "14662", "snowman'ssheathut" },
            { "14661", "papermacheteut" },
            { "2752", "ringofparamountdefenset4" },
            { "2757", "ringofparamounthealtht4" },
            { "2759", "ringofexaltedattackt5" },
            { "2760", "ringofexalteddefenset5" },
            { "2761", "ringofexaltedspeedt5" },
            { "2762", "ringofexaltedvitalityt5" },
            { "2763", "ringofexaltedwisdomt5" },
            { "2764", "ringofexalteddexterityt5" },
            { "2765", "ringofexaltedhealtht5" },
            { "2766", "ringofexaltedmagict5" },
            { "9016", "almandineringofwrathut" },
            { "8960", "ringoftheburningsunut" },
            { "2979", "ringofunboundattackt6" },
            { "2980", "ringofunbounddefenset6" },
            { "2981", "ringofunboundspeedt6" },
            { "2982", "ringofunboundvitalityt6" },
            { "2983", "ringofunboundwisdomt6" },
            { "2984", "ringofunbounddexterityt6" },
            { "2985", "ringofunboundhealtht6" },
            { "2986", "ringofunboundmagict6" },
            { "2990", "ringofdecadesut" },
            { "2976", "ringofthesphinxut" },
            { "3121", "experimentalringut" },
            { "3167", "candyringut" },
            { "2878", "amuletofdispersionut" },
            { "2625", "snakeeyeringut" },
            { "25788", "oryxmasornament" },
            { "4058", "maskofanubisut" },
            { "4059", "maskoflightningut" },
            { "4061", "maskofmucusut" },
            { "4060", "maskofcnidariaut" },
            { "19250", "crystalkeyut" },
            { "32722", "enchantediceshardut" },
            { "-19464", "esben'sweddingringut" },
            { "9053", "geb'sringofwisdomut" },
            { "9057", "ringofthecovetousheartut" },
            { "9061", "legacyringofpurewishesut" },
            { "8611", "legacyspectralringofhorrorsut" },
            { "8618", "legacyforgottenringut" },
            { "9669", "theforgottenringut" },
            { "3091", "coralringut" },
            { "3104", "ringofdivinefaithut" },
            { "3111", "captain'sringut" },
            { "1800", "spider'seyeringut" },
            { "2109", "fairyringut" },
            { "3184", "goldenankh" },
            { "3185", "eyeofosiris" },
            { "3186", "pharaoh'smask" },
            { "3187", "goldencockle" },
            { "3188", "goldenconch" },
            { "3189", "goldenhornconch" },
            { "3190", "goldennut" },
            { "3191", "goldenbolt" },
            { "3192", "goldenfemur" },
            { "3193", "goldenribcage" },
            { "3194", "goldenskull" },
            { "3195", "goldencandelabra" },
            { "3196", "holycross" },
            { "3197", "pearlnecklace" },
            { "3198", "goldenchalice" },
            { "3199", "rubygemstone" },
            { "9018", "thedeviltarotcard" },
            { "9019", "thesuntarotcard" },
            { "9020", "deathtarotcard" },
            { "9021", "thetowertarotcard" },
            { "9022", "themagiciantarotcard" },
            { "9023", "theworldtarotcard" },
            { "9024", "thechariottarotcard" },
            { "3861", "thefooltarotcard" },
            { "3205", "commonfelineegg" },
            { "3209", "commoncanineegg" },
            { "3213", "commonavianegg" },
            { "3217", "commonexoticegg" },
            { "3221", "commonfarmegg" },
            { "3225", "commonwoodlandegg" },
            { "3229", "commonreptileegg" },
            { "3233", "commoninsectegg" },
            { "3237", "commonpenguinegg" },
            { "3241", "commonaquaticegg" },
            { "3245", "commonspookyegg" },
            { "3249", "commonhumanoidegg" },
            { "3253", "common????egg" },
            { "3257", "commonautomatonegg" },
            { "3261", "commonmysteryegg" },
            { "-117", "anycommonpetegg" },
            { "3206", "uncommonfelineegg" },
            { "3210", "uncommoncanineegg" },
            { "3214", "uncommonavianegg" },
            { "3218", "uncommonexoticegg" },
            { "3222", "uncommonfarmegg" },
            { "3226", "uncommonwoodlandegg" },
            { "3230", "uncommonreptileegg" },
            { "3234", "uncommoninsectegg" },
            { "3238", "uncommonpenguinegg" },
            { "3242", "uncommonaquaticegg" },
            { "3246", "uncommonspookyegg" },
            { "3250", "uncommonhumanoidegg" },
            { "3254", "uncommon????egg" },
            { "3258", "uncommonautomatonegg" },
            { "3262", "uncommonmysteryegg" },
            { "-118", "anyuncommonpetegg" },
            { "3207", "rarefelineegg" },
            { "3215", "rareavianegg" },
            { "3219", "rareexoticegg" },
            { "3223", "rarefarmegg" },
            { "3227", "rarewoodlandegg" },
            { "3231", "rarereptileegg" },
            { "3239", "rarepenguinegg" },
            { "3247", "rarespookyegg" },
            { "3251", "rarehumanoidegg" },
            { "3255", "rare????egg" },
            { "3259", "rareautomatonegg" },
            { "3263", "raremysteryegg" },
            { "-119", "anyrarepetegg" },
            { "-101", "anyitemwith200ormorefeedpower" },
            { "-102", "anyitemwith300ormorefeedpower" },
            { "-103", "anyitemwith400ormorefeedpower" },
            { "-104", "anyitemwith450ormorefeedpower" },
            { "-105", "anyitemwith500ormorefeedpower" },
            { "-106", "anyitemwith550ormorefeedpower" },
            { "-107", "anyitemwith600ormorefeedpower" },
            { "-108", "anyitemwith650ormorefeedpower" },
            { "-109", "anyitemwith700ormorefeedpower" },
            { "-110", "anyitemwith800ormorefeedpower" },
            { "-111", "anyitemwith900ormorefeedpower" },
            { "-112", "anyitemwith1000ormorefeedpower" },
            { "-115", "anyitemwith1300ormorefeedpower" },
            { "-120", "anyuntiereditemproviding15commonforgematerialwhendismantled" },
            { "-122", "anyuntiereditemproviding15rareforgematerialwhendismantled" },
        };

        public static Dictionary<string, string> idToItemName = new()
        {
            { "2591", "Potion of Attack" },
            { "2593", "Potion of Speed" },
            { "2636", "Potion of Dexterity" },
            { "2613", "Potion of Wisdom" },
            { "2612", "Potion of Vitality" },
            { "2794", "Potion of Mana" },
            { "2793", "Potion of Life" },
            { "116", "Any stat pot" },
            { "9065", "Greater Potion of Defense" },
            { "9064", "Greater Potion of Attack" },
            { "9066", "Greater Potion of Speed" },
            { "9069", "Greater Potion of Dexterity" },
            { "9068", "Greater Potion of Wisdom" },
            { "9067", "Greater Potion of Vitality" },
            { "9071", "Greater Potion of Mana" },
            { "9070", "Greater Potion of Life" },
            { "1826", "Wine Cellar Incantation" },
            { "10024", "Helmet Rune" },
            { "10023", "Shield Rune" },
            { "10022", "Sword Rune" },
            { "1808", "Tomb of the Ancients Key" },
            { "3089", "Ocean Trench Key" },
            { "1802", "Abyss of Demons Key" },
            { "3107", "Manor Key" },
            { "3133", "Beachzone Key" },
            { "3170", "Candy Key" },
            { "3278", "Deadwater Docks Key" },
            { "3311", "Battle Nexus Key" },
            { "3293", "Shatters Key" },
            { "8852", "Shaitan's Key" },
            { "29804", "Puppet Master's Encore Key" },
            { "303", "Mountain Temple Key" },
            { "4252", "The Nest Key" },
            { "2991", "Lost Halls Key" },
            { "2555", "Reef Key" },
            { "3872", "Mad God Mayhem Key" },
            { "13984", "Secluded Thicket Key" },
            { "1404", "Cursed Library Key" },
            { "9326", "Heroic Undead Lair Key" },
            { "9325", "Heroic Abyss of Demons Key" },
            { "1413", "Malogia Key" },
            { "1415", "Forax Key" },
            { "1412", "Fungal Cavern Key" },
            { "19301", "The Third Dimension Key" },
            { "1799", "Healing Ichor" },
            { "3105", "Holy Water" },
            { "2868", "Fire Water" },
            { "2875", "Muscat" },
            { "2871", "Melon Liqueur" },
            { "3090", "Coral Juice" },
            { "2736", "Minor Health Potion" },
            { "2781", "Minor Magic Potion" },
            { "3109", "Ghost Pirate Rum" },
            { "3137", "Transformation Potion" },
            { "3267", "Saint Paddy's Brew" },
            { "3129", "Bahama Sunrise" },
            { "3130", "Blue Paradise" },
            { "3131", "Pink Passion Breeze" },
            { "3132", "Lime Jungle Bay" },
            { "1409", "Server Heart" },
            { "2835", "Effusion of Defense" },
            { "3436", "Effusion of Attack" },
            { "3437", "Effusion of Speed" },
            { "2832", "Effusion of Dexterity" },
            { "3439 ", "Effusion of Wisdom" },
            { "3438", "Effusion of Vitality" },
            { "2833", "Effusion of Life" },
            { "3432", "Tincture of Attack" },
            { "3433", "Tincture of Speed" },
            { "2828", "Tincture of Dexterity" },
            { "19080", "Amaranth Nildrop" },
            { "19083", "Scarlet Nildrop" },
            { "19085", "Azure Nildrop" },
            { "19084", "Crimson Nildrop" },
            { "19086", "Hazel Nildrop" },
            { "19087", "Teal Nildrop" },
            { "19079", "Force Nildrop" },
            { "19078", "Cinder Nildrop" },
            { "9077", "Blood Nildrop" },
            { "2799", "White Drake Egg" },
            { "2800", "Blue Drake Egg" },
            { "2801", "Orange Drake Egg" },
            { "2802", "Green Drake Egg" },
            { "2641", "Magic Mushroom" },
            { "5407", "Valentine" },
            { "8779", "Potion of Health1" },
            { "8798", "Potion of Health2" },
            { "8814", "Slime Archer Skin" },
            { "8815", "Brigand Skin" },
            { "8827", "Agent Skin" },
            { "8828", "Slime Knight Skin" },
            { "8829", "Slime Priest Skin" },
            { "8830", "Bashing Bride Skin" },
            { "8831", "Eligible Bachelor Skin" },
            { "8858", "Nun Skin" },
            { "8859", "Witch Doctor Skin" },
            { "8860", "Sorceress Skin" },
            { "8861 ", "Artemis Skin" },
            { "8781", "Shoveguy Skin" },
            { "8812", "Scarlett Skin" },
            { "9615", "Slime Ninja Skin" },
            { "8850", "Slime Wizard Skin" },
            { "8851", "Deadly Vixen Skin" },
            { "8856", "Stanley the Spring Bunny Skin" },
            { "8993", "Nexus no Miko Skin" },
            { "8995", "Drow Trickster Skin" },
            { "8983", "B.B. Wolf Skin" },
            { "8984", "Lil Red Skin" },
            { "8783", "Holy Avenger Skin" },
            { "8796", "Ranger Skin" },
            { "8985", "King Knifeula Skin" },
            { "9011", "Witch Skin" },
            { "8980", "Platinum Knight Skin" },
            { "8981", "Platinum Warrior Skin" },
            { "8982", "Platinum Rogue Skin" },
            { "9033", "Slime Sorcerer Skin" },
            { "9034", "Slime Trickster Skin" },
            { "9035", "Slime Mystic Skin" },
            { "9036", "Slime Huntress Skin" },
            { "9037", "Slime Necromancer Skin" },
            { "9038", "Slime Assassin Skin" },
            { "9039", "Slime Paladin Skin" },
            { "9040", "Slime Rogue Skin" },
            { "9041", "Slime Warrior Skin" },
            { "29769", "Puppet Master Skin" },
            { "29772,", "Jester Skin" },
            { "9074", "Ghost Huntress Skin" },
            { "9075", "Skeleton Warrior Skin" },
            { "29819", "Huntsman Skin" },
            { "29820", "Demon Spawn Skin" },
            { "29821", "Hunchback Skin" },
            { "29822", "Vampiress Skin" },
            { "29823", "Frankensteins Monster Skin" },
            { "29824", "Jack the Ripper Skin" },
            { "29825", "Death Skin" },
            { "29826", "Tiny Avatar Skin" },
            { "20827", "Zombie Nurse Skin" },
            { "29828", "Ascended Sorcerer Skin" },
            { "29829", "Mischievous Imp Skin" },
            { "29830", "Vampire Hunter Skin" },
            { "29831", "Poltergeist Skin" },
            { "29832", "Dark Elf Huntress Skin" },
            { "9076", "Infected Skin" },
            { "3312", "Santa Skin" },
            { "3313", "Little Helper Skin" },
            { "3320", "Iceman Skin" },
            { "6874", "Santa Trickster Skin" },
            { "8319", "Oryxmas Rogue Skin" },
            { "8320", "Oryxmas Archer Skin" },
            { "8321", "Oryxmas Wizard Skin" },
            { "8322", "Oryxmas Priest Skin" },
            { "8323", "Oryxmas Warrior Skin" },
            { "8324 ", "Oryxmas Knight Skin" },
            { "8325", "Oryxmas Paladin Skin" },
            { "8326", "Oryxmas Assassin Skin" },
            { "8327", "Oryxmas Necromancer Skin" },
            { "8328", "Oryxmas Huntress Skin" },
            { "8329", "Oryxmas Mystic Skin" },
            { "8330", "Oryxmas Trickster Skin" },
            { "8331", "Oryxmas Sorcerer Skin" },
            { "8332", "Oryxmas Ninja Skin" },
            { "19660", "Oryxmas Samurai Skin" },
            { "9382", "Slime Bard Skin" },
            { "9390", "Oryxmas Bard Skin" },
            { "30720", "Slime Summoner Skin" },
            { "30804", "Oryxmas Summoner Skin" },
            { "31233", "Oryxmas Kensei Skin" },
            { "2721", "Staff of Diabolic Secrets T10" },
            { "2722", "Staff of Astral Knowledge T11" },
            { "2824", "Staff of the Cosmic Whole T12" },
            { "2513", "Staff of the Vital Unity T13" },
            { "3075", "Staff of Extreme Prejudice UT" },
            { "5847 ", "Staff of Iceblast UT" },
            { "3108", "Anatis Staff UT" },
            { "3306", "KoalaPOW UT" },
            { "8843", "Staff of Adoration UT" },
            { "8857", "Staff of the Rising Sun UT" },
            { "8998", "Barely Attuned Magic Thingy UT" },
            { "3859", "Staff of Horrific Knowledge UT" },
            { "9059", "The Phylactery UT" },
            { "9086", "Staff of Yuletide Carols UT" },
            { "8615", "Legacy Sentient Staff UT" },
            { "14493", "Staff of Silver Wings UT" },
            { "2112", "Spirit Staff UT" },
            { "25688", "Foramite Staff UT" },
            { "6860", "Frosty's Walking Stick UT" },
            { "1894", "Staff of Esben UT" },
            { "12069", "Screwdriver Staff UT" },
            { "20977", "Staff of the Saint UT" },
            { "1394", "K.I.D.D. Force UT" },
            { "2694", "Wand of Shadow T10" },
            { "2695", "Wand of Ancient Warning T11" },
            { "2806", "Wand of Recompense T12" },
            { "2506", "Wand of Evocation T13" },
            { "3076", "Wand of the Bulwark UT" },
            { "5848", "Eternal Snowflake Wand UT" },
            { "3101", "St. Abraham's Wand UT" },
            { "3123", "Conducting Wand UT" },
            { "3307", "Spicy Wand of Spice UT" },
            { "8999", "Lethargic Sentience UT" },
            { "8854", "Wand of Egg" },
            { "3856", "Wand of Ancient Terror UT" },
            { "9055", "Wand of Geb UT" },
            { "9084", "Present Dispensing Wand UT" },
            { "14494", "Wand of the Summoned One UT" },
            { "6861", "Winter's Breath Wand UT" },
            { "24834", "Soul's Guidance UT" },
            { "5138,", "Frozen Wand UT" },
            { "1398", "Caduceus of Current Craziness UT" },
            { "2635", "Sprite Wand UT" },
            { "2700", "Bow of Fey Magic T10" },
            { "2701", "Bow of Innocent Blood T11" },
            { "2818", "Bow of Covert Havens T12" },
            { "2508", "Bow of Mystical Energy T13" },
            { "6858", "Icicle Launcher UT" },
            { "3074", "Doom Bow UT" },
            { "8961", "Bow of the Morning Star UT" },
            { "25696", "Sun's Judgement UT" },
            { "3088", "Coral Bow UT" },
            { "5849", "Arctic Bow UT" },
            { "3308", "Robobow UT" },
            { "8997", "Precisely Calibrated Stringstick UT" },
            { "9610", "Bow of Eternal Frost UT" },
            { "14492", "Bow of the Sky's Glory UT" },
            { "12067", "Nail Gun Bow UT" },
            { "5706", "Clover Bow UT" },
            { "1397", "Butter Bow UT" },
            { "2697", "Emeraldshard Dagger T10" },
            { "2698", "Agateclaw Dagger T11" },
            { "2815", "Dagger of Foul Malevolence T12" },
            { "2502", "Dagger of Sinister Deeds T13" },
            { "2849", "Chicken Leg of Doom UT" },
            { "3106", "Bone Dagger UT" },
            { "3113", "Spirit Dagger UT" },
            { "1801", "Poison Fang Dagger UT" },
            { "3309", "Sunshine Shiv UT" },
            { "8845", "Heartfind Dagger UT" },
            { "9002", "Dagger of the Amethyst Prism UT" },
            { "9000", "Toy Knife UT" },
            { "3857", "Dagger of the Terrible Talon UT" },
            { "8608", "Legacy Etherite Dagger UT" },
            { "9085", "An Icicle UT" },
            { "14491", "Dagger of Eternal Chaos UT" },
            { "12068", "Spatula Dagger UT" },
            { "2201", "Dagger of the Hasteful Rabbit UT" },
            { "20983", "Prismatic Slasher UT" },
        };
    }
}
