using System.Collections.Generic;

namespace Common.Utilities
{
    public static class Definitions
    {
        private static readonly Dictionary<string, string> definitionsDictionary = new()
        {
            { "2591", "Potion of Attack" },
            { "2593", "Potion of Speed" },
            { "2636", "Potion of Dexterity" },
            { "2613", "Potion of Wisdom" },
            { "2612", "Potion of Vitality" },
            { "2794", "Potion of Mana" },
            { "2793", "Potion of Life" },
            { "116", "Any stat pot" },
            { "9065", "Greater Potion of Defense" },
            { "9064", "Greater Potion of Attack" },
            { "9066", "Greater Potion of Speed" },
            { "9069", "Greater Potion of Dexterity" },
            { "9068", "Greater Potion of Wisdom" },
            { "9067", "Greater Potion of Vitality" },
            { "9071", "Greater Potion of Mana" },
            { "9070", "Greater Potion of Life" },
            { "1826", "Wine Cellar Incantation" },
            { "10024", "Helmet Rune" },
            { "10023", "Shield Rune" },
            { "10022", "Sword Rune" },
            { "1808", "Tomb of the Ancients Key" },
            { "3089", "Ocean Trench Key" },
            { "1802", "Abyss of Demons Key" },
            { "3107", "Manor Key" },
            { "3133", "Beachzone Key" },
            { "3170", "Candy Key" },
            { "3278", "Deadwater Docks Key" },
            { "3311", "Battle Nexus Key" },
            { "3293", "Shatters Key" },
            { "8852", "Shaitan's Key" },
            { "29804", "Puppet Master's Encore Key" },
            { "303", "Mountain Temple Key" },
            { "4252", "The Nest Key" },
            { "2991", "Lost Halls Key" },
            { "2555", "Reef Key" },
            { "3872", "Mad God Mayhem Key" },
            { "13984", "Secluded Thicket Key" },
            { "1404", "Cursed Library Key" },
            { "9326", "Heroic Undead Lair Key" },
            { "9325", "Heroic Abyss of Demons Key" },
            { "1413", "Malogia Key" },
            { "1415", "Forax Key" },
            { "1412", "Fungal Cavern Key" },
            { "19301", "The Third Dimension Key" },
            { "1799", "Healing Ichor" },
            { "3105", "Holy Water" },
            { "2868", "Fire Water" },
            { "2875", "Muscat" },
            { "2871", "Melon Liqueur" },
            { "3090", "Coral Juice" },
            { "2736", "Minor Health Potion" },
            { "2781", "Minor Magic Potion" },
            { "3109", "Ghost Pirate Rum" },
            { "3137", "Transformation Potion" },
            { "3267", "Saint Paddy's Brew" },
            { "3129", "Bahama Sunrise" },
            { "3130", "Blue Paradise" },
            { "3131", "Pink Passion Breeze" },
            { "3132", "Lime Jungle Bay" },
            { "1409", "Server Heart" },
            { "2835", "Effusion of Defense" },
            { "3436", "Effusion of Attack" },
            { "3437", "Effusion of Speed" },
            { "2832", "Effusion of Dexterity" },
            { "3439 ", "Effusion of Wisdom" },
            { "3438", "Effusion of Vitality" },
            { "2833", "Effusion of Life" },
            { "3432", "Tincture of Attack" },
            { "3433", "Tincture of Speed" },
            { "2828", "Tincture of Dexterity" },
            { "19080", "Amaranth Nildrop" },
            { "19083", "Scarlet Nildrop" },
            { "19085", "Azure Nildrop" },
            { "19084", "Crimson Nildrop" },
            { "19086", "Hazel Nildrop" },
            { "19087", "Teal Nildrop" },
            { "19079", "Force Nildrop" },
            { "19078", "Cinder Nildrop" },
            { "9077", "Blood Nildrop" },
            { "2799", "White Drake Egg" },
            { "2800", "Blue Drake Egg" },
            { "2801", "Orange Drake Egg" },
            { "2802", "Green Drake Egg" },
            { "2641", "Magic Mushroom" },
            { "5407", "Valentine" },
            { "8779", "Potion of Health1" },
            { "8798", "Potion of Health2" },
            { "8814", "Slime Archer Skin" },
            { "8815", "Brigand Skin" },
            { "8827", "Agent Skin" },
            { "8828", "Slime Knight Skin" },
            { "8829", "Slime Priest Skin" },
            { "8830", "Bashing Bride Skin" },
            { "8831", "Eligible Bachelor Skin" },
            { "8858", "Nun Skin" },
            { "8859", "Witch Doctor Skin" },
            { "8860", "Sorceress Skin" },
            { "8861 ", "Artemis Skin" },
            { "8781", "Shoveguy Skin" },
            { "8812", "Scarlett Skin" },
            { "9615", "Slime Ninja Skin" },
            { "8850", "Slime Wizard Skin" },
            { "8851", "Deadly Vixen Skin" },
            { "8856", "Stanley the Spring Bunny Skin" },
            { "8993", "Nexus no Miko Skin" },
            { "8995", "Drow Trickster Skin" },
            { "8983", "B.B. Wolf Skin" },
            { "8984", "Lil Red Skin" },
            { "8783", "Holy Avenger Skin" },
            { "8796", "Ranger Skin" },
            { "8985", "King Knifeula Skin" },
            { "9011", "Witch Skin" },
            { "8980", "Platinum Knight Skin" },
            { "8981", "Platinum Warrior Skin" },
            { "8982", "Platinum Rogue Skin" },
            { "9033", "Slime Sorcerer Skin" },
            { "9034", "Slime Trickster Skin" },
            { "9035", "Slime Mystic Skin" },
            { "9036", "Slime Huntress Skin" },
            { "9037", "Slime Necromancer Skin" },
            { "9038", "Slime Assassin Skin" },
            { "9039", "Slime Paladin Skin" },
            { "9040", "Slime Rogue Skin" },
            { "9041", "Slime Warrior Skin" },
            { "29769", "Puppet Master Skin" },
            { "29772,", "Jester Skin" },
            { "9074", "Ghost Huntress Skin" },
            { "9075", "Skeleton Warrior Skin" },
            { "29819", "Huntsman Skin" },
            { "29820", "Demon Spawn Skin" },
            { "29821", "Hunchback Skin" },
            { "29822", "Vampiress Skin" },
            { "29823", "Frankensteins Monster Skin" },
            { "29824", "Jack the Ripper Skin" },
            { "29825", "Death Skin" },
            { "29826", "Tiny Avatar Skin" },
            { "20827", "Zombie Nurse Skin" },
            { "29828", "Ascended Sorcerer Skin" },
            { "29829", "Mischievous Imp Skin" },
            { "29830", "Vampire Hunter Skin" },
            { "29831", "Poltergeist Skin" },
            { "29832", "Dark Elf Huntress Skin" },
            { "9076", "Infected Skin" },
            { "3312", "Santa Skin" },
            { "3313", "Little Helper Skin" },
            { "3320", "Iceman Skin" },
            { "6874", "Santa Trickster Skin" },
            { "8319", "Oryxmas Rogue Skin" },
            { "8320", "Oryxmas Archer Skin" },
            { "8321", "Oryxmas Wizard Skin" },
            { "8322", "Oryxmas Priest Skin" },
            { "8323", "Oryxmas Warrior Skin" },
            { "8324 ", "Oryxmas Knight Skin" },
            { "8325", "Oryxmas Paladin Skin" },
            { "8326", "Oryxmas Assassin Skin" },
            { "8327", "Oryxmas Necromancer Skin" },
            { "8328", "Oryxmas Huntress Skin" },
            { "8329", "Oryxmas Mystic Skin" },
            { "8330", "Oryxmas Trickster Skin" },
            { "8331", "Oryxmas Sorcerer Skin" },
            { "8332", "Oryxmas Ninja Skin" },
            { "19660", "Oryxmas Samurai Skin" },
            { "9382", "Slime Bard Skin" },
            { "9390", "Oryxmas Bard Skin" },
            { "30720", "Slime Summoner Skin" },
            { "30804", "Oryxmas Summoner Skin" },
            { "31233", "Oryxmas Kensei Skin" },
            { "2721", "Staff of Diabolic Secrets T10" },
            { "2722", "Staff of Astral Knowledge T11" },
            { "2824", "Staff of the Cosmic Whole T12" },
            { "2513", "Staff of the Vital Unity T13" },
            { "3075", "Staff of Extreme Prejudice UT" },
            { "5847 ", "Staff of Iceblast UT" },
            { "3108", "Anatis Staff UT" },
            { "3306", "KoalaPOW UT" },
            { "8843", "Staff of Adoration UT" },
            { "8857", "Staff of the Rising Sun UT" },
            { "8998", "Barely Attuned Magic Thingy UT" },
            { "3859", "Staff of Horrific Knowledge UT" },
            { "9059", "The Phylactery UT" },
            { "9086", "Staff of Yuletide Carols UT" },
            { "8615", "Legacy Sentient Staff UT" },
            { "14493", "Staff of Silver Wings UT" },
            { "2112", "Spirit Staff UT" },
            { "25688", "Foramite Staff UT" },
            { "6860", "Frosty's Walking Stick UT" },
            { "1894", "Staff of Esben UT" },
            { "12069", "Screwdriver Staff UT" },
            { "20977", "Staff of the Saint UT" },
            { "1394", "K.I.D.D. Force UT" },
            { "2694", "Wand of Shadow T10" },
            { "2695", "Wand of Ancient Warning T11" },
            { "2806", "Wand of Recompense T12" },
            { "2506", "Wand of Evocation T13" },
            { "3076", "Wand of the Bulwark UT" },
            { "5848", "Eternal Snowflake Wand UT" },
            { "3101", "St. Abraham's Wand UT" },
            { "3123", "Conducting Wand UT" },
            { "3307", "Spicy Wand of Spice UT" },
            { "8999", "Lethargic Sentience UT" },
            { "8854", "Wand of Egg" },
            { "3856", "Wand of Ancient Terror UT" },
            { "9055", "Wand of Geb UT" },
            { "9084", "Present Dispensing Wand UT" },
            { "14494", "Wand of the Summoned One UT" },
            { "6861", "Winter's Breath Wand UT" },
            { "24834", "Soul's Guidance UT" },
            { "5138,", "Frozen Wand UT" },
            { "1398", "Caduceus of Current Craziness UT" },
            { "2635", "Sprite Wand UT" },
            { "2700", "Bow of Fey Magic T10" },
            { "2701", "Bow of Innocent Blood T11" },
            { "2818", "Bow of Covert Havens T12" },
            { "2508", "Bow of Mystical Energy T13" },
            { "6858", "Icicle Launcher UT" },
            { "3074", "Doom Bow UT" },
            { "8961", "Bow of the Morning Star UT" },
            { "25696", "Sun's Judgement UT" },
            { "3088", "Coral Bow UT" },
            { "5849", "Arctic Bow UT" },
            { "3308", "Robobow UT" },
            { "8997", "Precisely Calibrated Stringstick UT" },
            { "9610", "Bow of Eternal Frost UT" },
            { "14492", "Bow of the Sky's Glory UT" },
            { "12067", "Nail Gun Bow UT" },
            { "5706", "Clover Bow UT" },
            { "1397", "Butter Bow UT" },
            { "2697", "Emeraldshard Dagger T10" },
            { "2698", "Agateclaw Dagger T11" },
            { "2815", "Dagger of Foul Malevolence T12" },
            { "2502", "Dagger of Sinister Deeds T13" },
            { "2849", "Chicken Leg of Doom UT" },
            { "3106", "Bone Dagger UT" },
            { "3113", "Spirit Dagger UT" },
            { "1801", "Poison Fang Dagger UT" },
            { "3309", "Sunshine Shiv UT" },
            { "8845", "Heartfind Dagger UT" },
            { "9002", "Dagger of the Amethyst Prism UT" },
            { "9000", "Toy Knife UT" },
            { "3857", "Dagger of the Terrible Talon UT" },
            { "8608", "Legacy Etherite Dagger UT" },
            { "9085", "An Icicle UT" },
            { "14491", "Dagger of Eternal Chaos UT" },
            { "12068", "Spatula Dagger UT" },
            { "2201", "Dagger of the Hasteful Rabbit UT" },
            { "20983", "Prismatic Slasher UT" },
        };

        public static string GetItemNameFromItemId(string itemId)
        {
            if (!definitionsDictionary.ContainsKey(itemId)) return "Could not find item id in the dictionary";
            return definitionsDictionary[itemId];
        }


        // Used at all? e.g. {1234, ringofdecadesut}
        public static string GetItemNameNoSpacesFromItemId(string itemId)
        {
            var idToItemNameDictionary = definitionsDictionary;
            foreach (var (key, val) in idToItemNameDictionary)
            {
                idToItemNameDictionary.Add(key, $"{val.ToLower().Replace(" ", "")}");
            }

            if (!idToItemNameDictionary.ContainsKey(idToItemNameDictionary[itemId])) return "Could not find item id in the dictionary";

            return idToItemNameDictionary[itemId];
        }

        public static string GetItemIdFromItemNameNoSpaces(string itemNameNoSpaces)
        {
            var itemNameToIdDictionary = ConvertToItemNameToIdNoSpacesDictionary();
            if (!itemNameToIdDictionary.ContainsKey(itemNameNoSpaces)) return "Could not find item name in the dictionary";
            return itemNameToIdDictionary[itemNameNoSpaces];
        }

        private static Dictionary<string, string> ConvertToItemNameToIdNoSpacesDictionary()
        {
            var itemNameToIdDictionary = new Dictionary<string, string>();

            foreach (var (key, val) in definitionsDictionary)
            {
                itemNameToIdDictionary.Add($"{val.ToLower().Replace(" ", "")}", key);
            }

            return itemNameToIdDictionary;
        }
    }
}
